### PR TITLE
Add slide style customization slot

### PR DESCRIPTION
**Pull request by ncovercash**
This adds a new `slide` customization slot for styles!  I couldn't find where the docs at https://yet-another-react-lightbox.com/customization were stored, but those would need to be updated too.

- [x] I have followed the 'Sending a Pull Request' section of the [contributing guide](https://github.com/igordanchenko/yet-another-react-lightbox/blob/main/CONTRIBUTING.md#sending-a-pull-request)

### CODE REVIEW

**Comment by igordanchenko** [comment]
Can you give me an example of how this customization slot will be used? The idea behind customization slots was to provide an easy way to customize the default styles of visual elements (e.g. backdrop color, buttons styles, etc.)

**Comment by ncovercash** [comment]
My use case with this was to adjust the flexbox configuration of the `slide`, to change `flexDirection` to `column` in order to change some parts of how the caption description is displayed relative to the slide. I've accomplished it in my current project with CSS class overrides, but thought this would be a good addition to the first-class customization slots and fit with the others.

If you think this is too niche/doesn't fit, feel free to close this; it just seemed to be missing from the other available slots.  IMO, additional configuration is always a good option

**Comment by ncovercash** [comment]
image
Here's an example of what I did, where the `slide` needed `flex-direction: column` to make the caption description appear below the image, rather than on top of it

**Comment by igordanchenko** [comment]
Thank you for providing these additional details. This is very helpful.

**Review by igordanchenko — APPROVED** [review]

**Comment by igordanchenko** [comment]
Thank you for your contribution!

**Pull request merged**
